baseURL = "https://bogomolov.work/blog/"
languageCode = "en-us"
title = "The Archive"
theme = "hugo-theme-nostyleplease"
summaryLength = 32

[module]
  [module.hugoVersion]
    extended = true
    min      = "0.41.0"

[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true
        title = true

  [markup.highlight]
    anchorLineNos      = false
    codeFences         = true
    guessSyntax        = false
    hl_Lines           = ""
    hl_inline          = false
    lineAnchors        = ""
    lineNoStart        = 1
    lineNos            = false
    lineNumbersInTable = true
    noClasses          = true
    noHl               = false
    style              = "rrt"
    tabWidth           = 4

  [markup.tableOfContents]
    startLevel = 2
    endLevel   = 3
    ordered    = false

[sitemap]
  priority = 0.7

[params]
  favicon = "/favicon.ico"
  googleAnalytics = "G-950H2PH48S"

  [params.theme_config]
    appearance        = "auto"
    back_home_text    = "<-"
    date_format       = "2006-01-02"
    isListGroupByDate = false
    isShowFooter      = true
    show_description  = true
