baseURL = "https://bogomolov.work/blog/"
languageCode = "en"
title = "The Archive"
theme = "hugo-theme-nostyleplease"
summaryLength = 32

[module]
  [module.hugoVersion]
    extended = true
    min      = "0.41.0"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.parser]
      wrapStandAloneImageWithinParagraph = false
      [markup.goldmark.parser.attribute]
        block = true
    [markup.goldmark.renderHooks]
      [markup.goldmark.renderHooks.image]
        useEmbedded = "fallback"
      [markup.goldmark.renderHooks.link]
        useEmbedded = "fallback"
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.typographer]
        apostrophe = "’"
        leftDoubleQuote = "“"
        rightDoubleQuote = "”"
        leftSingleQuote = "‘"
        rightSingleQuote = "’"
        ellipsis = "…"
        emDash = "—"
        enDash = "–"
        leftAngleQuote = "«"
        rightAngleQuote = "»"
  [markup.highlight]
    style = "rrt"

[sitemap]
  priority = 0.7

[params]
  googleAnalytics = "G-950H2PH48S"
  adSense = "ca-pub-5202129729848909"
  yandexMetrika = 100343675
  metaPixel = 2627430184120255
  summary = "These data-spirits, my scrap-code prayer, are offered to the Machine God."
  defaultImg = "img/the-archive.jpg"
  showFullTextinRSS = false

  [params.theme_config]
    appearance        = "auto"
    back_home_text    = "← Back"
    date_format       = "2006-01-02"
    isListGroupByDate = false
    show_description  = true
