baseURL = "https://bogomolov.work/"
languageCode = "en"
title = "The Archive"
theme = "hugo-theme-nostyleplease"
summaryLength = 32
disableKinds = ["taxonomy", "term"]
disableHugoGeneratorInject = true

[outputs]
home = ["HTML", "RSS"]
section = ["HTML"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.parser]
      wrapStandAloneImageWithinParagraph = false
      [markup.goldmark.parser.attribute]
        block = true
    [markup.goldmark.renderHooks]
      [markup.goldmark.renderHooks.image]
        useEmbedded = "fallback"
      [markup.goldmark.renderHooks.link]
        useEmbedded = "fallback"
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.typographer]
        apostrophe = "’"
        leftDoubleQuote = "“"
        rightDoubleQuote = "”"
        leftSingleQuote = "‘"
        rightSingleQuote = "’"
        ellipsis = "…"
        emDash = "—"
        enDash = "–"
        leftAngleQuote = "«"
        rightAngleQuote = "»"
  [markup.highlight]
    style = "rrt"

[sitemap]
  priority = 0.7

[params]
  # metaPixel = 2627430184120255 // disabled forever, due to pagespeed.web.dev
  # adSense = "ca-pub-5202129729848909"
  # googleAnalytics = "G-950H2PH48S"
  # yandexMetrika = 100343675
  # ---
  grafanaFaro = "https://faro-collector-prod-eu-west-2.grafana.net/collect/280a442f2880e6eb5e953a7169416ccf"
  summary = "These data-spirits, my scrap-code prayer, are offered to the Machine God."
  defaultImg = "img/the-archive.jpg"
  showFullTextinRSS = false

  [params.theme_config]
    date_format       = "2006-01-02"
    back_home_text    = "← Back"
